#:import COURSES screens.cadastro.COURSES

<EditStudentScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 32
        spacing: 12

        Label:
            text: "Editar aluno"
            font_size: "24sp"

        TextInput:
            id: rm_input
            hint_text: "RM"
            multiline: False
            size_hint_y: None
            height: "48dp"

        TextInput:
            id: name_input
            hint_text: "Nome"
            multiline: False
            size_hint_y: None
            height: "48dp"

        Spinner:
            id: course_input
            text: "Selecione o curso"
            values: COURSES
            size_hint_y: None
            height: "48dp"

        Label:
            id: feedback
            text: ""
            size_hint_y: None
            height: "40dp"

        Button:
            text: "Salvar alterações"
            size_hint_y: None
            height: "48dp"
            on_release: root.save_student()

        Button:
            text: "Cancelar"
            size_hint_y: None
            height: "48dp"
            on_release: root.manager.current = "alunos"
