<HomeScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 32
        spacing: 16

        Label:
            text: "ClassBase"
            font_size: "28sp"

        Label:
            text: "Gerenciamento de alunos"

        Button:
            text: "Cadastrar aluno"
            size_hint_y: None
            height: "48dp"
            on_release: root.manager.current = "cadastro"

        Button:
            text: "Consultar alunos"
            size_hint_y: None
            height: "48dp"
            on_release: root.manager.current = "alunos"

        Button:
            text: "Sair"
            size_hint_y: None
            height: "48dp"
            on_release: root.manager.current = "login"
