<LoginScreen>:
    BoxLayout:
        orientation: "vertical"
        padding: 32
        spacing: 16

        Label:
            text: "ClassBase"
            font_size: "32sp"

        TextInput:
            hint_text: "Usuário"
            multiline: False
            size_hint_y: None
            height: "48dp"

        TextInput:
            hint_text: "Senha"
            password: True
            multiline: False
            size_hint_y: None
            height: "48dp"

        Button:
            text: "Entrar"
            size_hint_y: None
            height: "48dp"
            on_release: root.manager.current = "home"
